name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t apple-health-importer:latest
    - name: Build the arm Docker image
      run: docker build . --file Dockerfile -t apple-health-importer:arm64 --platform linux/arm64/v8
    - name: Login to registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login hub.docker.com -u itspa1 --password-stdin
    - name: Push to registry
      run: |
            docker push itspa1/apple-health-importer:latest
            docker tag apple-health-importer:arm64 itspa1/apple-health-importer:arm64
            docker push itspa1/apple-health-importer:arm64
